#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { readCatalog, root } = require('./catalog.js');
const { generate } = require('./gen-distribution.js');
const { parseFrontmatter } = require('./gen-skills-tree.js');
const { convertedSkillName } = require('./portable-artifacts.js');

const META = path.join(root, 'scripts', 'distribution-meta.json');
const OUTPUT = path.join(root, 'docs', 'pi-package-filters.md');

const unsupported = (entry) => entry.artifacts.every((artifact) => artifact.dispositions.pi.disposition === 'unsupported');

function closure(name, byName, seen = new Set()) {
  if (seen.has(name)) return [];
  seen.add(name);
  const entry = byName.get(name);
  if (!entry || unsupported(entry)) return [];
  return [entry, ...entry.runtimeDependencies.flatMap((dependency) => closure(dependency, byName, seen))];
}

function skillNames(entry) {
  const names = [];
  for (const artifact of entry.artifacts) {
    if (artifact.dispositions.pi.disposition === 'unsupported') continue;
    if (artifact.kind === 'skill') {
      const file = path.join(entry.sourceRoot, artifact.path);
      const name = parseFrontmatter(fs.readFileSync(file, 'utf8')).name;
      if (!name) throw new Error(`${entry.name}/${artifact.path}: skill has no name`);
      names.push(name);
    } else if (['command', 'agent'].includes(artifact.kind)) {
      names.push(convertedSkillName(entry, artifact));
    }
  }
  return names;
}

function bundleFilters(inventory) {
  const byName = new Map(inventory.map((entry) => [entry.name, entry]));
  return inventory
    .filter((entry) => entry.artifacts.some((artifact) => artifact.kind === 'bundle'))
    .map((bundle) => ({
      name: bundle.name,
      skills: [...new Set(closure(bundle.name, byName).flatMap(skillNames))].sort(),
    }));
}

function validatePiBundleFilters(inventory, skillsRoot) {
  for (const bundle of bundleFilters(inventory)) {
    for (const name of bundle.skills) {
      if (!fs.existsSync(path.join(skillsRoot, name, 'SKILL.md'))) {
        throw new Error(`${bundle.name}: bundle filter references missing skill ${name}`);
      }
    }
  }
}

function renderPiBundleFilters(inventory) {
  const sections = [];
  for (const bundle of bundleFilters(inventory)) {
    const names = bundle.skills;
    const settings = {
      packages: [{
        source: 'git:github.com/filippolmt/skills',
        autoload: false,
        skills: names.map((name) => `+skills/${name}`),
      }],
    };
    sections.push(`## \`${bundle.name}\`\n\n\`\`\`json\n${JSON.stringify(settings, null, 2)}\n\`\`\``);
  }
  return [
    '# pi bundle filters', '',
    '<!-- generated by `node scripts/gen-pi.js`; do not edit -->', '',
    'pi installs this repository as one package. These filters enable each Claude bundle’s portable runtime closure; hooks and MCP limitations remain documented in `distribution-parity.md`.', '',
    ...sections, '',
  ].join('\n');
}

module.exports = { renderPiBundleFilters, validatePiBundleFilters };

if (require.main === module) {
  const check = process.argv.includes('--check');
  const metadata = JSON.parse(fs.readFileSync(META, 'utf8'));
  const { plugins } = readCatalog();
  const { inventory } = generate(plugins, metadata);
  validatePiBundleFilters(inventory, path.join(root, 'skills'));
  const output = renderPiBundleFilters(inventory);
  if (check) {
    if (fs.existsSync(OUTPUT) && fs.readFileSync(OUTPUT, 'utf8') === output) {
      console.log('pi package filters are in sync.');
      process.exit(0);
    }
    console.error('pi package filters are out of date. Run: node scripts/gen-pi.js');
    process.exit(1);
  }
  fs.writeFileSync(OUTPUT, output);
  console.log('pi package filters generated.');
}
